#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ResponsibleAging.Resource", IsApplication=true)]

namespace ResponsibleAging
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int c = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int d = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int e = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int f = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int g = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int h = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int round = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int AfterNoon = 2131034124;
			
			// aapt resource value: 0x7f050012
			public const int MainMenu = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int Morning = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int Night = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int button4 = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int button5 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int imageButton1 = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int imageButton2 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int imageButton3 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int imageButton4 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int imageButton5 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int imageButton6 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int imageButton7 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int imageButton8 = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int tableLayout1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int tableRow2 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int tableRow3 = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConnectToWatch = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Exercise = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Heartrate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Medication = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MedicationAfternoon = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MedicationMorning = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MedicationNight = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
